# Generated by Django 5.2.4 on 2025-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_reg_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(upload_to='products/')),
                ('productname', models.CharField(max_length=100)),
                ('productcode', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
            ],
        ),
    ]
