# Generated by Django 5.2.4 on 2025-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
